### ISSUE TITLE
Unable to build docker image

### ISSUE THREAD

**Issue by gabsone** [jhipster/jhipster-registry#377] opened 2019-08-30 15:08 UTC
##### **Overview of the issue**
when try to build docker image with command:
`docker build .`
i get this error:
`/bin/sh: 1: ./mvnw: not found
The command '/bin/sh -c apt-get update &&     apt-get install build-essential -y &&     cd /code/ &&     rm -Rf target node_modules &&     chmod +x /code/mvnw &&     sleep 1 &&     JHI_DISABLE_WEBPACK_LOGS=true ./mvnw package -ntp -Pprod -DskipTests &&     mv /code/target/*.jar /jhipster-registry.jar &&     apt-get clean &&     rm -Rf /code/ /root/.m2 /root/.cache /tmp/* /var/lib/apt/lists/* /var/tmp/*' returned a non-zero code: 127
`
##### **JHipster Registry Version(s)**
5.0.2

##### **Docker version**
Docker version 19.03.1, build 74b1e89

**Comment by ruddell** [comment] 2019-08-30 19:41
Can you please add all of the steps to reproduce, starting from an empty directory?  Cloning this repository and running `docker build .` works on my end.

If `./mvnw` is not found, did the [previous step](https://github.com/jhipster/jhipster-registry/blob/master/Dockerfile#L2) of adding this repository code into the docker image succeed?

**Comment by gabsone** [comment] 2019-08-30 19:44
Hi,
I only cloned the repo and try to build. 
The mvnw file is present and all previous command are executed correctly. 

Thanks.

**Comment by jkoorts** [comment] 2019-09-16 13:58
Not working for me as well. Both for the Dockerfile in root and in /src/main/docker. 

#######
What is the difference between the two eg. when do you use the one and not the other? Drives me nuts not knowing the answer.
#######

My setup: Win 10 with docker for windows using Linux containers:

My steps:

C:\>mkdir testy

C:\>cd testy

C:\testy>git clone https://github.com/jhipster/jhipster-registry.git
Cloning into 'jhipster-registry'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 9267 (delta 7), reused 10 (delta 2), pack-reused 9227
Receiving objects: 100% (9267/9267), 5.70 MiB | 3.37 MiB/s, done.
Resolving deltas: 100% (4611/4611), done.

C:\testy>cd jhipster-registry

C:\testy\jhipster-registry>docker build .
Sending build context to Docker daemon  9.249MB
Step 1/9 : FROM openjdk:8 as builder
 ---> e8d00769c8a8
Step 2/9 : ADD . /code/
 ---> 488e084c1394
Step 3/9 : RUN     apt-get update &&     apt-get install build-essential -y &&     cd /code/ &&     rm -Rf target node_modules &&     chmod +x /code/mvnw &&     sleep 1 &&     JHI_DISABLE_WEBPACK_LOGS=true ./mvnw package -ntp -Pprod -DskipTests &&     mv /code/targ
et/*.jar /jhipster-registry.jar &&     apt-get clean &&     rm -Rf /code/ /root/.m2 /root/.cache /tmp/* /var/lib/apt/lists/* /var/tmp/*
 ---> Running in 1a726aa3f960
Ign:1 http://deb.debian.org/debian stretch InRelease
Get:2 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Get:3 http://deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:4 http://deb.debian.org/debian stretch Release [118 kB]
Get:5 http://deb.debian.org/debian stretch-updates/main amd64 Packages [27.4 kB]
Get:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [503 kB]
Get:7 http://deb.debian.org/debian stretch Release.gpg [2365 B]
Get:8 http://deb.debian.org/debian stretch/main amd64 Packages [7086 kB]
Fetched 7922 kB in 2s (2800 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  binutils cpp cpp-6 dpkg-dev fakeroot g++ g++-6 gcc gcc-6
  libalgorithm-diff-perl libalgorithm-diff-xs-perl libalgorithm-merge-perl
  libasan3 libatomic1 libc-dev-bin libc6-dev libcc1-0 libcilkrts5 libdpkg-perl
  libfakeroot libfile-fcntllock-perl libgcc-6-dev libgomp1 libisl15 libitm1
  liblocale-gettext-perl liblsan0 libmpc3 libmpfr4 libmpx2 libquadmath0
  libstdc++-6-dev libtsan0 libubsan0 linux-libc-dev make manpages manpages-dev
  patch
Suggested packages:
  binutils-doc cpp-doc gcc-6-locales debian-keyring g++-multilib
  g++-6-multilib gcc-6-doc libstdc++6-6-dbg gcc-multilib autoconf automake
  libtool flex bison gdb gcc-doc gcc-6-multilib libgcc1-dbg libgomp1-dbg
  libitm1-dbg libatomic1-dbg libasan3-dbg liblsan0-dbg libtsan0-dbg
  libubsan0-dbg libcilkrts5-dbg libmpx2-dbg libquadmath0-dbg glibc-doc
  libstdc++-6-doc make-doc man-browser ed diffutils-doc
The following NEW packages will be installed:
  binutils build-essential cpp cpp-6 dpkg-dev fakeroot g++ g++-6 gcc gcc-6
  libalgorithm-diff-perl libalgorithm-diff-xs-perl libalgorithm-merge-perl
  libasan3 libatomic1 libc-dev-bin libc6-dev libcc1-0 libcilkrts5 libdpkg-perl
  libfakeroot libfile-fcntllock-perl libgcc-6-dev libgomp1 libisl15 libitm1
  liblocale-gettext-perl liblsan0 libmpc3 libmpfr4 libmpx2 libquadmath0
  libstdc++-6-dev libtsan0 libubsan0 linux-libc-dev make manpages manpages-dev
  patch
0 upgraded, 40 newly installed, 0 to remove and 0 not upgraded.
Need to get 41.4 MB of archives.
After this operation, 165 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian stretch/main amd64 liblocale-gettext-perl amd64 1.07-3+b1 [18.7 kB]
Get:2 http://deb.debian.org/debian stretch/main amd64 manpages all 4.10-2 [1222 kB]
Get:3 http://deb.debian.org/debian stretch/main amd64 binutils amd64 2.28-5 [3770 kB]
Get:4 http://deb.debian.org/debian stretch/main amd64 libc-dev-bin amd64 2.24-11+deb9u4 [259 kB]
Get:5 http://deb.debian.org/debian stretch/main amd64 linux-libc-dev amd64 4.9.189-3 [1446 kB]
Get:6 http://deb.debian.org/debian stretch/main amd64 libc6-dev amd64 2.24-11+deb9u4 [2364 kB]
Get:7 http://deb.debian.org/debian stretch/main amd64 libisl15 amd64 0.18-1 [564 kB]
Get:8 http://deb.debian.org/debian stretch/main amd64 libmpfr4 amd64 3.1.5-1 [556 kB]
Get:9 http://deb.debian.org/debian stretch/main amd64 libmpc3 amd64 1.0.3-1+b2 [39.9 kB]
Get:10 http://deb.debian.org/debian stretch/main amd64 cpp-6 amd64 6.3.0-18+deb9u1 [6584 kB]
Get:11 http://deb.debian.org/debian stretch/main amd64 cpp amd64 4:6.3.0-4 [18.7 kB]
Get:12 http://deb.debian.org/debian stretch/main amd64 libcc1-0 amd64 6.3.0-18+deb9u1 [30.6 kB]
Get:13 http://deb.debian.org/debian stretch/main amd64 libgomp1 amd64 6.3.0-18+deb9u1 [73.3 kB]
Get:14 http://deb.debian.org/debian stretch/main amd64 libitm1 amd64 6.3.0-18+deb9u1 [27.3 kB]
Get:15 http://deb.debian.org/debian stretch/main amd64 libatomic1 amd64 6.3.0-18+deb9u1 [8966 B]
Get:16 http://deb.debian.org/debian stretch/main amd64 libasan3 amd64 6.3.0-18+deb9u1 [311 kB]
Get:17 http://deb.debian.org/debian stretch/main amd64 liblsan0 amd64 6.3.0-18+deb9u1 [115 kB]
Get:18 http://deb.debian.org/debian stretch/main amd64 libtsan0 amd64 6.3.0-18+deb9u1 [257 kB]
Get:19 http://deb.debian.org/debian stretch/main amd64 libubsan0 amd64 6.3.0-18+deb9u1 [107 kB]
Get:20 http://deb.debian.org/debian stretch/main amd64 libcilkrts5 amd64 6.3.0-18+deb9u1 [40.5 kB]
Get:21 http://deb.debian.org/debian stretch/main amd64 libmpx2 amd64 6.3.0-18+deb9u1 [11.2 kB]
Get:22 http://deb.debian.org/debian stretch/main amd64 libquadmath0 amd64 6.3.0-18+deb9u1 [131 kB]
Get:23 http://deb.debian.org/debian stretch/main amd64 libgcc-6-dev amd64 6.3.0-18+deb9u1 [2296 kB]
Get:24 http://deb.debian.org/debian stretch/main amd64 gcc-6 amd64 6.3.0-18+deb9u1 [6900 kB]
Get:25 http://deb.debian.org/debian stretch/main amd64 gcc amd64 4:6.3.0-4 [5196 B]
Get:26 http://deb.debian.org/debian stretch/main amd64 libstdc++-6-dev amd64 6.3.0-18+deb9u1 [1420 kB]
Get:27 http://deb.debian.org/debian stretch/main amd64 g++-6 amd64 6.3.0-18+deb9u1 [7094 kB]
Get:28 http://deb.debian.org/debian stretch/main amd64 g++ amd64 4:6.3.0-4 [1546 B]
Get:29 http://deb.debian.org/debian stretch/main amd64 make amd64 4.1-9.1 [302 kB]
Get:30 http://deb.debian.org/debian stretch/main amd64 libdpkg-perl all 1.18.25 [1287 kB]
Get:31 http://deb.debian.org/debian stretch/main amd64 patch amd64 2.7.5-1+deb9u2 [112 kB]
Get:32 http://deb.debian.org/debian stretch/main amd64 dpkg-dev all 1.18.25 [1595 kB]
Get:33 http://deb.debian.org/debian stretch/main amd64 build-essential amd64 12.3 [7346 B]
Get:34 http://deb.debian.org/debian stretch/main amd64 libfakeroot amd64 1.21-3.1 [45.7 kB]
Get:35 http://deb.debian.org/debian stretch/main amd64 fakeroot amd64 1.21-3.1 [85.6 kB]
Get:36 http://deb.debian.org/debian stretch/main amd64 libalgorithm-diff-perl all 1.19.03-1 [48.7 kB]
Get:37 http://deb.debian.org/debian stretch/main amd64 libalgorithm-diff-xs-perl amd64 0.04-4+b2 [11.6 kB]
Get:38 http://deb.debian.org/debian stretch/main amd64 libalgorithm-merge-perl all 0.08-3 [12.7 kB]
Get:39 http://deb.debian.org/debian stretch/main amd64 libfile-fcntllock-perl amd64 0.22-3+b2 [35.3 kB]
Get:40 http://deb.debian.org/debian stretch/main amd64 manpages-dev all 4.10-2 [2145 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 41.4 MB in 7s (5826 kB/s)
Selecting previously unselected package liblocale-gettext-perl.
(Reading database ... 12447 files and directories currently installed.)
Preparing to unpack .../00-liblocale-gettext-perl_1.07-3+b1_amd64.deb ...
Unpacking liblocale-gettext-perl (1.07-3+b1) ...
Selecting previously unselected package manpages.
Preparing to unpack .../01-manpages_4.10-2_all.deb ...
Unpacking manpages (4.10-2) ...
Selecting previously unselected package binutils.
Preparing to unpack .../02-binutils_2.28-5_amd64.deb ...
Unpacking binutils (2.28-5) ...
Selecting previously unselected package libc-dev-bin.
Preparing to unpack .../03-libc-dev-bin_2.24-11+deb9u4_amd64.deb ...
Unpacking libc-dev-bin (2.24-11+deb9u4) ...
Selecting previously unselected package linux-libc-dev:amd64.
Preparing to unpack .../04-linux-libc-dev_4.9.189-3_amd64.deb ...
Unpacking linux-libc-dev:amd64 (4.9.189-3) ...
Selecting previously unselected package libc6-dev:amd64.
Preparing to unpack .../05-libc6-dev_2.24-11+deb9u4_amd64.deb ...
Unpacking libc6-dev:amd64 (2.24-11+deb9u4) ...
Selecting previously unselected package libisl15:amd64.
Preparing to unpack .../06-libisl15_0.18-1_amd64.deb ...
Unpacking libisl15:amd64 (0.18-1) ...
Selecting previously unselected package libmpfr4:amd64.
Preparing to unpack .../07-libmpfr4_3.1.5-1_amd64.deb ...
Unpacking libmpfr4:amd64 (3.1.5-1) ...
Selecting previously unselected package libmpc3:amd64.
Preparing to unpack .../08-libmpc3_1.0.3-1+b2_amd64.deb ...
Unpacking libmpc3:amd64 (1.0.3-1+b2) ...
Selecting previously unselected package cpp-6.
Preparing to unpack .../09-cpp-6_6.3.0-18+deb9u1_amd64.deb ...
Unpacking cpp-6 (6.3.0-18+deb9u1) ...
Selecting previously unselected package cpp.
Preparing to unpack .../10-cpp_4%3a6.3.0-4_amd64.deb ...
Unpacking cpp (4:6.3.0-4) ...
Selecting previously unselected package libcc1-0:amd64.
Preparing to unpack .../11-libcc1-0_6.3.0-18+deb9u1_amd64.deb ...
Unpacking libcc1-0:amd64 (6.3.0-18+deb9u1) ...
Selecting previously unselected package libgomp1:amd64.
Preparing to unpack .../12-libgomp1_6.3.0-18+deb9u1_amd64.deb ...
Unpacking libgomp1:amd64 (6.3.0-18+deb9u1) ...
Selecting previously unselected package libitm1:amd64.
Preparing to unpack .../13-libitm1_6.3.0-18+deb9u1_amd64.deb ...
Unpacking libitm1:amd64 (6.3.0-18+deb9u1) ...
Selecting previously unselected package libatomic1:amd64.
Preparing to unpack .../14-libatomic1_6.3.0-18+deb9u1_amd64.deb ...
Unpacking libatomic1:amd64 (6.3.0-18+deb9u1) ...
Selecting previously unselected package libasan3:amd64.
Preparing to unpack .../15-libasan3_6.3.0-18+deb9u1_amd64.deb ...
Unpacking libasan3:amd64 (6.3.0-18+deb9u1) ...
Selecting previously unselected package liblsan0:amd64.
Preparing to unpack .../16-liblsan0_6.3.0-18+deb9u1_amd64.deb ...
Unpacking liblsan0:amd64 (6.3.0-18+deb9u1) ...
Selecting previously unselected package libtsan0:amd64.
Preparing to unpack .../17-libtsan0_6.3.0-18+deb9u1_amd64.deb ...
Unpacking libtsan0:amd64 (6.3.0-18+deb9u1) ...
Selecting previously unselected package libubsan0:amd64.
Preparing to unpack .../18-libubsan0_6.3.0-18+deb9u1_amd64.deb ...
Unpacking libubsan0:amd64 (6.3.0-18+deb9u1) ...
Selecting previously unselected package libcilkrts5:amd64.
Preparing to unpack .../19-libcilkrts5_6.3.0-18+deb9u1_amd64.deb ...
Unpacking libcilkrts5:amd64 (6.3.0-18+deb9u1) ...
Selecting previously unselected package libmpx2:amd64.
Preparing to unpack .../20-libmpx2_6.3.0-18+deb9u1_amd64.deb ...
Unpacking libmpx2:amd64 (6.3.0-18+deb9u1) ...
Selecting previously unselected package libquadmath0:amd64.
Preparing to unpack .../21-libquadmath0_6.3.0-18+deb9u1_amd64.deb ...
Unpacking libquadmath0:amd64 (6.3.0-18+deb9u1) ...
Selecting previously unselected package libgcc-6-dev:amd64.
Preparing to unpack .../22-libgcc-6-dev_6.3.0-18+deb9u1_amd64.deb ...
Unpacking libgcc-6-dev:amd64 (6.3.0-18+deb9u1) ...
Selecting previously unselected package gcc-6.
Preparing to unpack .../23-gcc-6_6.3.0-18+deb9u1_amd64.deb ...
Unpacking gcc-6 (6.3.0-18+deb9u1) ...
Selecting previously unselected package gcc.
Preparing to unpack .../24-gcc_4%3a6.3.0-4_amd64.deb ...
Unpacking gcc (4:6.3.0-4) ...
Selecting previously unselected package libstdc++-6-dev:amd64.
Preparing to unpack .../25-libstdc++-6-dev_6.3.0-18+deb9u1_amd64.deb ...
Unpacking libstdc++-6-dev:amd64 (6.3.0-18+deb9u1) ...
Selecting previously unselected package g++-6.
Preparing to unpack .../26-g++-6_6.3.0-18+deb9u1_amd64.deb ...
Unpacking g++-6 (6.3.0-18+deb9u1) ...
Selecting previously unselected package g++.
Preparing to unpack .../27-g++_4%3a6.3.0-4_amd64.deb ...
Unpacking g++ (4:6.3.0-4) ...
Selecting previously unselected package make.
Preparing to unpack .../28-make_4.1-9.1_amd64.deb ...
Unpacking make (4.1-9.1) ...
Selecting previously unselected package libdpkg-perl.
Preparing to unpack .../29-libdpkg-perl_1.18.25_all.deb ...
Unpacking libdpkg-perl (1.18.25) ...
Selecting previously unselected package patch.
Preparing to unpack .../30-patch_2.7.5-1+deb9u2_amd64.deb ...
Unpacking patch (2.7.5-1+deb9u2) ...
Selecting previously unselected package dpkg-dev.
Preparing to unpack .../31-dpkg-dev_1.18.25_all.deb ...
Unpacking dpkg-dev (1.18.25) ...
Selecting previously unselected package build-essential.
Preparing to unpack .../32-build-essential_12.3_amd64.deb ...
Unpacking build-essential (12.3) ...
Selecting previously unselected package libfakeroot:amd64.
Preparing to unpack .../33-libfakeroot_1.21-3.1_amd64.deb ...
Unpacking libfakeroot:amd64 (1.21-3.1) ...
Selecting previously unselected package fakeroot.
Preparing to unpack .../34-fakeroot_1.21-3.1_amd64.deb ...
Unpacking fakeroot (1.21-3.1) ...
Selecting previously unselected package libalgorithm-diff-perl.
Preparing to unpack .../35-libalgorithm-diff-perl_1.19.03-1_all.deb ...
Unpacking libalgorithm-diff-perl (1.19.03-1) ...
Selecting previously unselected package libalgorithm-diff-xs-perl.
Preparing to unpack .../36-libalgorithm-diff-xs-perl_0.04-4+b2_amd64.deb ...
Unpacking libalgorithm-diff-xs-perl (0.04-4+b2) ...
Selecting previously unselected package libalgorithm-merge-perl.
Preparing to unpack .../37-libalgorithm-merge-perl_0.08-3_all.deb ...
Unpacking libalgorithm-merge-perl (0.08-3) ...
Selecting previously unselected package libfile-fcntllock-perl.
Preparing to unpack .../38-libfile-fcntllock-perl_0.22-3+b2_amd64.deb ...
Unpacking libfile-fcntllock-perl (0.22-3+b2) ...
Selecting previously unselected package manpages-dev.
Preparing to unpack .../39-manpages-dev_4.10-2_all.deb ...
Unpacking manpages-dev (4.10-2) ...
Setting up libquadmath0:amd64 (6.3.0-18+deb9u1) ...
Setting up libgomp1:amd64 (6.3.0-18+deb9u1) ...
Setting up libatomic1:amd64 (6.3.0-18+deb9u1) ...
Setting up manpages (4.10-2) ...
Setting up libcc1-0:amd64 (6.3.0-18+deb9u1) ...
Setting up make (4.1-9.1) ...
Setting up libasan3:amd64 (6.3.0-18+deb9u1) ...
Setting up libcilkrts5:amd64 (6.3.0-18+deb9u1) ...
Setting up libubsan0:amd64 (6.3.0-18+deb9u1) ...
Setting up libtsan0:amd64 (6.3.0-18+deb9u1) ...
Setting up linux-libc-dev:amd64 (4.9.189-3) ...
Setting up libdpkg-perl (1.18.25) ...
Setting up liblsan0:amd64 (6.3.0-18+deb9u1) ...
Setting up libfile-fcntllock-perl (0.22-3+b2) ...
Setting up libmpx2:amd64 (6.3.0-18+deb9u1) ...
Setting up libisl15:amd64 (0.18-1) ...
Setting up patch (2.7.5-1+deb9u2) ...
Processing triggers for libc-bin (2.24-11+deb9u4) ...
Setting up libfakeroot:amd64 (1.21-3.1) ...
Setting up libalgorithm-diff-perl (1.19.03-1) ...
Setting up liblocale-gettext-perl (1.07-3+b1) ...
Setting up libmpfr4:amd64 (3.1.5-1) ...
Setting up libmpc3:amd64 (1.0.3-1+b2) ...
Setting up binutils (2.28-5) ...
Setting up cpp-6 (6.3.0-18+deb9u1) ...
Setting up libc-dev-bin (2.24-11+deb9u4) ...
Setting up manpages-dev (4.10-2) ...
Setting up libc6-dev:amd64 (2.24-11+deb9u4) ...
Setting up libitm1:amd64 (6.3.0-18+deb9u1) ...
Setting up cpp (4:6.3.0-4) ...
Setting up libgcc-6-dev:amd64 (6.3.0-18+deb9u1) ...
Setting up libstdc++-6-dev:amd64 (6.3.0-18+deb9u1) ...
Setting up fakeroot (1.21-3.1) ...
update-alternatives: using /usr/bin/fakeroot-sysv to provide /usr/bin/fakeroot (fakeroot) in auto mode
Setting up gcc-6 (6.3.0-18+deb9u1) ...
Setting up g++-6 (6.3.0-18+deb9u1) ...
Setting up libalgorithm-merge-perl (0.08-3) ...
Setting up dpkg-dev (1.18.25) ...
Setting up libalgorithm-diff-xs-perl (0.04-4+b2) ...
Setting up gcc (4:6.3.0-4) ...
Setting up g++ (4:6.3.0-4) ...
update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode
Setting up build-essential (12.3) ...
Processing triggers for libc-bin (2.24-11+deb9u4) ...
/bin/sh: 1: ./mvnw: not found
The command '/bin/sh -c apt-get update &&     apt-get install build-essential -y &&     cd /code/ &&     rm -Rf target node_modules &&     chmod +x /code/mvnw &&     sleep 1 &&     JHI_DISABLE_WEBPACK_LOGS=true ./mvnw package -ntp -Pprod -DskipTests &&     mv /code
/target/*.jar /jhipster-registry.jar &&     apt-get clean &&     rm -Rf /code/ /root/.m2 /root/.cache /tmp/* /var/lib/apt/lists/* /var/tmp/*' returned a non-zero code: 127

**Comment by jkoorts** [comment] 2019-09-16 13:59
Here the steps for the other Docker file:

C:\testy\jhipster-registry>cd src/main/docker

C:\testy\jhipster-registry\src\main\docker>docker build .
Sending build context to Docker daemon  68.61kB
Step 1/10 : FROM openjdk:11-jre-slim-stretch
 ---> a71b975306d9
Step 2/10 : ENV SPRING_OUTPUT_ANSI_ENABLED=ALWAYS     JHIPSTER_SLEEP=0     JAVA_OPTS=""
 ---> Using cache
 ---> 8d7aac79cadb
Step 3/10 : RUN adduser -D -s /bin/sh jhipster
 ---> Running in a0c3a991312c
Option d is ambiguous (debug, disabled-login, disabled-password)
Option s is ambiguous (shell, system)
adduser [--home DIR] [--shell SHELL] [--no-create-home] [--uid ID]
[--firstuid ID] [--lastuid ID] [--gecos GECOS] [--ingroup GROUP | --gid ID]
[--disabled-password] [--disabled-login] [--add_extra_groups] USER
   Add a normal user

adduser --system [--home DIR] [--shell SHELL] [--no-create-home] [--uid ID]
[--gecos GECOS] [--group | --ingroup GROUP | --gid ID] [--disabled-password]
[--disabled-login] [--add_extra_groups] USER
   Add a system user

adduser --group [--gid ID] GROUP
addgroup [--gid ID] GROUP
   Add a user group

addgroup --system [--gid ID] GROUP
   Add a system group

adduser USER GROUP
   Add an existing user to an existing group

general options:
  --quiet | -q      don't give process information to stdout
  --force-badname   allow usernames which do not match the
                    NAME_REGEX configuration variable
  --help | -h       usage message
  --version | -v    version number and copyright
  --conf | -c FILE  use FILE as configuration file

The command '/bin/sh -c adduser -D -s /bin/sh jhipster' returned a non-zero code: 1

**Comment by ruddell** [comment] 2019-09-16 16:06
I still can't reproduce any issue with the Dockerfile present at the root of this project.  Regarding `src/main/docker/Dockerfile`, that one does not build (fails with the same error as the previous message).

It may have to do with Windows, I tested on Mac.  @jkoorts uses Windows but not sure about @gabsone.

**Comment by durantieu** [comment] 2019-10-10 13:09
Mine problem too!
Anybody knows which script should I have run to build a docker image of  jhipster-registry?

**Comment by jkoorts** [comment] 2019-10-10 13:11
get image from the docker registry. Leave the git project alone is my experience

**Comment by durantieu** [comment] 2019-10-10 13:11
I got an image by pulling it from docker-hub but what if I want to build that by using the /taget/*.jar generated from source code?

**Comment by ValeryTretyak** [comment] 2020-02-28 15:35
I couldn't build at all, saw an error: 
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project jhipster-registry: Fatal error compiling: invalid flag: --release ->
After all I followed advice from here (https://github.com/sensepost/mallet/issues/4)
and changed my pom, as described here:
https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html
Now it's built successfully.

**Comment by jvence** [comment] 2020-03-03 10:00
@ValeryTretyak Same problem here:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project jhipster-registry: Fatal error compiling: invalid flag: --release -> [Help 1]

**Comment by Matheus-Rangel** [comment] 2020-04-28 14:00
Make sure that the line ending of the mvnw is LF, when you clone the repository the git for Windows may change the line endings to CRLF.

**Comment by ruddell** [comment] 2020-09-27 15:18
Fixed by https://github.com/jhipster/jhipster-registry/pull/476 (error message and reproduction details match this issue)

**Closed by ruddell** 2020-09-27 15:18 UTC
