### ISSUE TITLE
Multiple entries with same key: springfox.documentation.spring.web.plugins.PathAndParametersEquivalence

### ISSUE THREAD

**Issue by magaton** [jhipster/jhipster-registry#209] opened 2017-11-24 13:34 UTC
##### **Overview of the issue**

When oauth2 profile is added
`
spring:
    application:
        name: jhipster-registry
    profiles:
        active: dev,native,oauth2
`
in bootstrap.yml

and I start registry with mvn clean spring-boot:run

I am getting exception during startup:
org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.IllegalArgumentException: Multiple entries with same key: springfox.documentation.spring.web.plugins.PathAndParametersEquivalence@2f188d30.wrap(springfox.documentation.spring.web.WebMvcRequestHandler@9c899e1)=[springfox.documentation.spring.web.WebMvcRequestHandler@9c899e1] and springfox.documentation.spring.web.plugins.PathAndParametersEquivalence@2f188d30.wrap(springfox.documentation.spring.web.WebMvcRequestHandler@17850343)=[springfox.documentation.spring.web.WebMvcRequestHandler@17850343]

##### **Motivation for or Use Case**

testing registry with OIDC

##### **Reproduce the error**

explained above

##### **JHipster Registry Version(s)**

3.2.3

##### **Browsers and Operating System**

Chrome, OSX Yosemite, JDK 1.8

**Comment by jdubois** [comment] 2017-11-24 13:40
The current JHipster version is v3.2.3, could you put the correct version? I doubt you are with v0.10.2.
And this just fails like that at startup? without doing anything? Could you try with the Docker image?

**Comment by magaton** [comment] 2017-11-24 13:44
ok, edited version in the issue itself.
yes, during startup

**Comment by magaton** [comment] 2017-11-24 13:54
Ok, here is what I've just found out:
./mvnw -Pdev,webpack works: doesn't blow with the reported exception but
mvn clean spring-boot:run -Pdev,webpack does blow.

mvn clean spring-boot:run -Pprod works and it runs dev,native, swagger and ouath2 spring profiles

I used to start my jhipster based apps with mvn clean spring-boot:run in the past, still haven't got used to ./mvnw way.

**Comment by pascalgrimaud** [comment] 2017-11-24 19:54
it's the same issue than: https://github.com/jhipster/jhipster-registry/issues/185

I'm closing this one, as, in the other issue, you have:
- the full stacktrace
- the steps to reproduce
- the link to the springfox's ticket

For resuming, the issue is on springfox's side.

**Closed by pascalgrimaud** 2017-11-24 19:54 UTC
