### ISSUE TITLE
Missing dependency NoClassDefFoundError: com/codahale/metrics/MetricRegistry

### ISSUE THREAD

**Issue by vwiencek** [jhipster/jhipster-registry#356] opened 2019-05-12 09:44 UTC
##### **Overview of the issue**

JHipster-registry fails to start with docker-compose configuration `jhipster-registry.yml`

##### **Motivation for or Use Case**

JHipster-registry seems to be failing in certain situations

##### **Reproduce the error**
my `jhipster-registry.yml` file
```
version: '2'
services:
  jhipster-registry:
    image: jhipster/jhipster-registry:v5.0.0
    volumes:
      - ./central-server-config:/central-config
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,uaa
      - SPRING_SECURITY_USER_PASSWORD=admin
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config
      - JHIPSTER_LOGGING_LOGSTASH_ENABLED=true
      - JHIPSTER_LOGGING_LOGSTASH_HOST=jhipster-logstash
      - JHIPSTER_METRICS_LOGS_ENABLED=false
      - JHIPSTER_METRICS_LOGS_REPORTFREQUENCY=60
      - JHIPSTER_SECURITY_CLIENT_AUTHORIZATION_TOKEN_SERVICE_ID=uaa
    ports:
      - 8761:8761
```

then start the docker server with 'docker-compose -f hipster-registry.yml up' and I get the following error

```
java.lang.IllegalStateException: Error processing condition on org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration.micrometerClock
   at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:64)
   at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108)

...

Caused by: java.lang.IllegalStateException: Failed to introspect Class [io.github.jhipster.config.metric.JHipsterLoggingMetricsExportConfiguration] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@254989ff]
   at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:507)
   at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:404)
   at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:389)
   at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:447)
   at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1688)

...

jhipster-registry_1  | Caused by: java.lang.NoClassDefFoundError: com/codahale/metrics/MetricRegistry
   at java.lang.Class.getDeclaredMethods0(Native Method)
   at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
   at java.lang.Class.getDeclaredMethods(Class.java:1975)
   at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:489)
   	... 45 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.codahale.metrics.MetricRegistry
   at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
   at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
   	... 49 common frames omitted
```

##### **Suggest a Fix**
Add the missing dependency ??

it seems that commenting those two lines prevent it to fail ...
```
#     - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
#     - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config
```

##### **JHipster Registry Version(s)**
v5.0.0

##### **Browsers and Operating System**
docker version 18.09.2 on macOS

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pdelaby** [comment] 2019-05-14 11:38
I have the same issue. 

For me, the problem came from the following shared configuration (in central-config or git config) 
```
jhipster:
    metrics:
        logs:
            enabled: true
```
There is a workaround :  I created a specific configuration for the registry to disable this value. 

1. Create a file (registry.yml) in the configuration folder/repository with this specific configuration set to `false`
```
# Workaround for registry v5.0.0
jhipster:
    metrics:
        logs:
            enabled: false
```
2. Then  and add a profile to the registry (with bootstrap.yml or docker environments args) so it takes this configuration. Here with docker-compose : 

```
environment:
 - SPRING_CLOUD_CONFIG_PROFILE=dev,registry
````

**Comment by clement26695** [comment] 2019-05-14 16:08
I think we removed by error one of the dropwizard dependency that was needed to export the metrics in the logs. Adding it should solve the issue. 

I'll take a look tomorrow

**Comment by mraible** [comment] 2019-05-14 16:15
I removed these dependencies when I [upgraded to JHipster 6](https://github.com/jhipster/jhipster-registry/pull/334) since we use Micrometer now. Why are dropwizard dependencies still needed?

**Comment by clement26695** [comment] 2019-05-15 07:57
It is needed here: https://github.com/jhipster/jhipster/blob/master/jhipster-framework/src/main/java/io/github/jhipster/config/metric/JHipsterLoggingMetricsExportConfiguration.java, in order to use this https://micrometer.io/docs/guide/consoleReporter, which is needed to make the JHipster console work. 

I think it is the only place it is needed, but I may have misconfigured it.

**Comment by PierreBesson** [comment] 2019-05-15 12:35
Please use a more recent docker-compose file generated by a recent version of jhipster. As the properties have changed in recent version.

>it seems that commenting those two lines prevent it to fail ...

    #     - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
    #     - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config

If you comment those lines then the registry will be unable to configure itself via the central-config directory.

**Comment by vwiencek** [comment] 2019-05-15 13:02
> If you comment those lines then the registry will be unable to configure itself via the central-config directory.

I realise now it's not the reason indeed.

> Please use a more recent docker-compose file generated by a recent version of jhipster. As the properties have changed in recent version.

I used the 6.0.0 version of hipster to generate the docker-compose file ; I'll try to reproduce with the 6.0.1 tomorrow.

thanks for your time

**Comment by mraible** [comment] 2019-05-17 14:09
I generated a microservices architecture with JHipster 6.0.1 today and indeed everything fails to work because of this issue.

```
Caused by: java.lang.NoClassDefFoundError: com/codahale/metrics/MetricRegistry
at java.lang.Class.getDeclaredMethods0(Native Method)
at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
at java.lang.Class.getDeclaredMethods(Class.java:1975)
at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:489)
... 27 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.codahale.metrics.MetricRegistry
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

This is a major issue IMO.

**Comment by mraible** [comment] 2019-05-17 14:11
The strange thing is this error doesn't happen when I run it for development:

```
SPRING_PROFILES_ACTIVE=dev,oauth2,native,swagger ./mvnw
```

I tried the `prod` profile and it still starts successfully.

**Comment by mraible** [comment] 2019-05-17 14:15
I can reproduce the issue using the following command:

```
JHIPSTER_METRICS_LOGS_ENABLED=true SPRING_PROFILES_ACTIVE=dev,oauth2,native,swagger ./mvnw
```

Now the question is, do we just add metrics back in as a dependency, or do we need to refactor things to work with Micrometer? @jhipster/developers

**Comment by PierreBesson** [comment] 2019-05-17 14:18
I don't understand. Do you guys mean that the jhipster-registry cannot start at all in v6.0.1 ? Or is it just when enabling log reporting to logstash ?

**Comment by PierreBesson** [comment] 2019-05-17 14:20
@clement26695, can you try to fix the bug in the coming days/week as I'm going to leave for vacation tomorrow ?

**Comment by mraible** [comment] 2019-05-17 14:20
@PierreBesson When I create a microservices stack with the following config, it doesn't run in Docker Compose.

```
application {
  config {
    baseName gateway,
    packageName com.okta.developer.gateway,
    applicationType gateway,
    authenticationType oauth2,
    prodDatabaseType postgresql,
    serviceDiscoveryType eureka,
    testFrameworks [protractor]
  }
  entities Blog, Post, Tag, Product
}

application {
  config {
    baseName blog,
    packageName com.okta.developer.blog,
    applicationType microservice,
    authenticationType oauth2,
    prodDatabaseType postgresql,
    serverPort 8081,
    serviceDiscoveryType eureka
  }
  entities Blog, Post, Tag
}

application {
  config {
    baseName store,
    packageName com.okta.developer.store,
    applicationType microservice,
    authenticationType oauth2,
    databaseType mongodb,
    devDatabaseType mongodb,
    prodDatabaseType mongodb,
    enableHibernateCache false,
    serverPort 8082,
    serviceDiscoveryType eureka
  }
  entities Product
}

entity Blog {
  name String required minlength(3),
  handle String required minlength(2)
}

entity Post {
  title String required,
  content TextBlob required,
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

entity Product {
  title String required,
  price BigDecimal required min(0),
  image ImageBlob
}

relationship ManyToOne {
  Blog{user(login)} to User,
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll
paginate Product with pagination

microservice Product with store
microservice Blog, Post, Tag with blog

// will be created under 'docker-compose' folder
deployment {
  deploymentType docker-compose
  appsFolders [gateway, blog, store]
  dockerRepositoryName "mraible"
  monitoring elk
  consoleOptions [zipkin]
}
```

**Comment by PierreBesson** [comment] 2019-05-17 14:49
Well in this case you know what to do 😉.

**Comment by mraible** [comment] 2019-05-18 22:48
Fixed by https://github.com/jhipster/jhipster-registry/pull/357.

**Closed by mraible** 2019-05-18 22:48 UTC
