### ISSUE TITLE
How to deal with multiple data sources problem in this framework?

### ISSUE THREAD

**Issue by kalle2017** [jhipster/jhipster-registry#341] opened 2019-04-02 08:58 UTC
How to deal with multiple data sources problem in this framework? I find nothing usefully to deal with such problem. So, can you help to give some suggests!

**Comment by jdubois** [comment] 2019-04-02 09:01
There is no datasource configured on the registry, do you mean this for jhipster/generator-jhispter ?

I'm closing this as this is not a bug report, and is probably on the wrong repo anyway.

**Closed by jdubois** 2019-04-02 09:01 UTC

**Comment by kalle2017** [comment] 2019-04-02 09:04
I mean that I want to use multiple datasouce in microservices and how should I do?

**Comment by jdubois** [comment] 2019-04-02 09:08
I'm sorry but this is the wrong repo (this is only for the registry), and this isn't a bug report but a general question.

Please have a look at https://www.jhipster.tech/help/ - I suggest you post this as a question on StackOverflow, this is the correct place for question, and this is were you will get the most help.
