### ISSUE TITLE
Secure the JHipster Registry(SSL)

### ISSUE THREAD

**Issue by GuruvaiahG** [jhipster/jhipster-registry#217] opened 2017-12-06 09:21 UTC
Hi I have enabled th SSL in application-dev.yml,
 
server:
    port: 8443
    ssl:
        key-store: keystore.p12
        key-store-password: genisys
        keyStoreType: PKCS12
        keyAlias: JHipsterRegistry

And i have build the Registry ,

   Application 'jhipster-registry' is running! Access URLs:
        Local:          https://localhost:8443
        Profile(s):     [dev, native]
When i call Local URL from browser i am getting below exception for login
This site can’t be reached

localhost unexpectedly closed the connection.
Try:
Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_CLOSED

Please let me know how to login into registry when we enable SSL in application-dev .yml.

**Comment by jdubois** [comment] 2017-12-06 12:04
Your conf looks correct, are you sure this isn't an issue on the browser side? Of course this depends on your browser, etc, and as you don't provide any information I can't help you.

For me this is a question for StackOverflow, as you are just configuring SSL on a normal Spring Boot app, and your conf looks OK to me.

**Comment by lsolisc** [comment] 2017-12-07 00:51
are you sure that keyAlias is the correct?, i had the same problem and was provoked by alias incorrect

**Comment by jdubois** [comment] 2017-12-07 14:18
This definitely looks like a Spring Boot configuration question, and not a bug -> I'm closing this as it's not a bug, please add question on StackOverflow using the "jhispter" tag, so more people can participate and learn.

**Closed by jdubois** 2017-12-07 14:18 UTC

**Comment by GuruvaiahG** [comment] 2017-12-08 05:51
How to add self signed SSL certificate to jHipster registry
 app?
